### ISSUE TITLE
Some voices refuse to install with invalid archive error

### ISSUE THREAD

**Issue by pitermach** [mush42/piper-nvda#2]
To reproduce:

- Download the Polish voice - https://github.com/rhasspy/piper/releases/download/v0.0.2/voice-pl-mls_6892-low.tar.gz
- Attempt to install it from the Piper settings
After selecting the file, I get an installation failed message and the log shows the following:
```
ERROR - external:globalPlugins.piper_voice_installer.SettingsPanel._get_process_tar_archive (12:02:32.001) - MainThread (8388):
Failed to install voice from archive
Traceback (most recent call last):
  File "C:\Users\piter\AppData\Roaming\nvda\addons\piper_neural_voices\globalPlugins\piper_voice_installer.py", line 78, in _get_process_tar_archive
    voice_key = PiperTextToSpeechSystem.install_voice(filepath, PIPER_VOICES_DIR)
  File "C:\Users\piter\AppData\Roaming\nvda\addons\piper_neural_voices\synthDrivers\piper_neural_voices\tts_system.py", line 280, in install_voice
    raise ValueError(f"Invalid voice archive: `{archive_path}`")
ValueError: Invalid voice archive: `D:\Downloads\voice-pl-mls_6892-low.tar.gz`
```

The Polish voice isn't the only one which fails in this way - I got an identical error when trying to install the Southern english voice. Others, like US English Lessac, Ryan and Danny, install with no problems.

**Comment by mush42** [comment]
@pitermach 

For now, just rename the voice file to have the following form:
voice-{language}-{name}-{quality}

replace language with the voice's language (e.g en-GB), name with the voice's name (e.g amy), and quality with the voice's quality (e.g low).

I'll fix this soon.

Best
Musharraf

**Comment by pitermach** [comment]
Thanks, I was able to get the voices installed following your instructions.

**Comment by CyrilleB79** [comment]
Same issue with "voice-fr-mls_1840-low.tar.gz".

Renaming the voice allows to install it. But there are still errors, e.g. opening the variant combobox.

**Comment by KevanGP** [comment]
En-GB Southern English Female will not install. I
m not sure where the logs are located or I'd paste the error. I did try redownloading the voice with same results.

**Comment by mush42** [comment]
@KevanGP  please take a look at my first comment above.

**Comment by tmthywynn8** [comment]
Would x-low voices populating improper fields be related to this issue? For example, installing the [Vietnamese vivos voice dataset][1] which does have a model card) produces the following:

|Name|Quality|Language|
|:---|:---|:---|
|X|Low|vi-VIVOS|

Voice model card button output:

```
[Window Title]
Info

[Content]
Model card information is unavailable for this voice

[OK]
```

[1]: https://github.com/rhasspy/piper/releases/download/v0.0.2/voice-vi-vivos-x-low.tar.gz

**Comment by austek** [comment]
Hi @pitermach — picking this up 3 years later on the [maintenance fork](https://github.com/austek/sonata-nvda).

Root cause: `VOICE_INFO_REGEX` in `voice_download.py` had `[a-z|_]+` as the `name` character class — letters, a literal pipe, and underscore, but **no digits** — so MLS voices like `mls_6892` / `mls_1840` couldn't match and fell through to the "Invalid voice archive" error.

Changed to `[a-z0-9_]+` (also dropped the unintentional `|`) in austek/sonata-nvda#15, now merged to `main`. Added a regression test covering the failing cases.

I'll come back here with the download link once the next release is tagged. Thanks for the original report.

**Comment by austek** [comment]
the latest release of the maintenance fork ships with the regex fix: https://github.com/austek/sonata-nvda/releases/latest

If you'd like to retest the original case (`voice-pl-mls_6892-low.tar.gz` etc.), it should install directly now without the rename workaround you and @mush42 worked around 3 years ago.
