### ISSUE TITLE
I cannot run Piper on my Windows 11 laptop, but in my desktop I can. Strange.

### ISSUE THREAD

**Issue by luiscarlos2000** [mush42/piper-nvda#20]
Downloaded the latest beta from the commit, and I even cannot understand how I got that error there, but in my laptop Piper doesn't work. Maybe my version of windows?
Log follows:
ERROR - globalPluginHandler.listPlugins (03:35:26.124) - MainThread (23152):
Error importing global plugin piper_voices_globalPlugin
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\LUIS CARLOS\AppData\Roaming\nvda\addons\piper_neural_voices\globalPlugins\piper_voices_globalPlugin\__init__.py", line 25, in <module>
    from piper_neural_voices import helpers as helpers
  File "C:\Users\LUIS CARLOS\AppData\Roaming\nvda\addons\piper_neural_voices\synthDrivers\piper_neural_voices\__init__.py", line 59, in <module>
    grpc_client.initialize()
  File "C:\Users\LUIS CARLOS\AppData\Roaming\nvda\addons\piper_neural_voices\synthDrivers\piper_neural_voices\grpc_client\__init__.py", line 52, in initialize
    start_grpc_server()
  File "C:\Users\LUIS CARLOS\AppData\Roaming\nvda\addons\piper_neural_voices\synthDrivers\piper_neural_voices\grpc_client\__init__.py", line 46, in start_grpc_server
    stderr=subprocess.DEVNULL,
  File "subprocess.pyc", line 800, in __init__
  File "subprocess.pyc", line 1207, in _execute_child
OSError: [WinError 193] %1 no es una aplicación Win32 válida
Not a valid win32 app? OK this is something... Maybe a very strange bug or some addon conflicting it... Is there a way to resolve it?

**Comment by mush42** [comment]
@luiscarlos2000 what is the processor architecture of your laptop?

I believe the TTS server binary is not compatible with your processor.

Make sure that you have a 64-bit Intel or AMD processor.
